//! Differential test: our Rust `title_sort`/`author_sort` against **Calibre's own
//! Python implementations**.
//!
//! `calibre_expected.json` was generated by exec'ing the real function bodies
//! out of Calibre 9.15's `calibre/ebooks/metadata/__init__.py` (with the tweak
//! values read from the installed `resources/default_tweaks.py`) over a corpus
//! of titles and author names. It is checked in, so this test needs neither
//! Python nor a Calibre install to run — but regenerating it is the only way to
//! test a *new* Calibre version, and `tests/interop_with_calibre.sh` does the
//! end-to-end check against a real binary.
//!
//! This exists because the first implementation of `title_sort` was written from
//! observed behaviour and used a 13-article list of the author's own invention.
//! Calibre's English list is exactly `A`, `The`, `An`. Comparing against the
//! real implementation is the only way that class of error gets caught.

use lorebook_calibre::functions::{author_sort, title_sort};
use serde_json::Value;

fn expected() -> Value {
    let raw = include_str!("calibre_expected.json");
    serde_json::from_str(raw).expect("calibre_expected.json must be valid JSON")
}

#[test]
fn title_sort_matches_calibre_exactly() {
    let v = expected();
    let cases = v["titles"].as_object().expect("titles must be an object");

    let mut mismatches: Vec<String> = Vec::new();
    for (input, want) in cases {
        let want = want.as_str().expect("expected values are strings");
        let got = title_sort(input);
        if got != want {
            mismatches.push(format!("  {input:?}: calibre={want:?} ours={got:?}"));
        }
    }

    assert!(
        mismatches.is_empty(),
        "{} of {} titles disagree with Calibre:\n{}",
        mismatches.len(),
        cases.len(),
        mismatches.join("\n")
    );
}

#[test]
fn author_sort_matches_calibre_exactly() {
    let v = expected();
    let cases = v["authors"].as_object().expect("authors must be an object");

    let mut mismatches: Vec<String> = Vec::new();
    for (input, want) in cases {
        let want = want.as_str().expect("expected values are strings");
        let got = author_sort(input);
        if got != want {
            mismatches.push(format!("  {input:?}: calibre={want:?} ours={got:?}"));
        }
    }

    assert!(
        mismatches.is_empty(),
        "{} of {} authors disagree with Calibre:\n{}",
        mismatches.len(),
        cases.len(),
        mismatches.join("\n")
    );
}

#[test]
fn the_corpus_is_worth_running() {
    // Guards against a regeneration that silently produced an empty or tiny
    // corpus, which would make the two tests above pass vacuously.
    let v = expected();
    assert!(
        v["titles"].as_object().unwrap().len() >= 50,
        "title corpus too small"
    );
    assert!(
        v["authors"].as_object().unwrap().len() >= 45,
        "author corpus too small"
    );
}
